{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "33a0b437",
   "metadata": {},
   "source": [
    "# Look at data\n",
    "Load LAZ → Clean & Filter → Register Epochs → Compute Height Change → Extract Features → Create ML Dataset\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "2d79c521",
   "metadata": {
    "ExecuteTime": {
     "end_time": "2025-10-29T23:39:40.076099Z",
     "start_time": "2025-10-29T23:39:29.314628Z"
    },
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[33mWARNING: Ignoring invalid distribution ~ympy (/opt/conda/envs/py311/lib/python3.11/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution ~ympy (/opt/conda/envs/py311/lib/python3.11/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mCollecting py4dgeo\n",
      "  Downloading py4dgeo-0.8.0.tar.gz (19.6 MB)\n",
      "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m19.6/19.6 MB\u001b[0m \u001b[31m69.2 MB/s\u001b[0m  \u001b[33m0:00:00\u001b[0m eta \u001b[36m0:00:01\u001b[0m\n",
      "\u001b[?25h  Installing build dependencies ... \u001b[?25ldone\n",
      "\u001b[?25h  Getting requirements to build wheel ... \u001b[?25ldone\n",
      "\u001b[?25h  Installing backend dependencies ... \u001b[?25ldone\n",
      "\u001b[?25h  Preparing metadata (pyproject.toml) ... \u001b[?25ldone\n",
      "\u001b[?25hCollecting dateparser (from py4dgeo)\n",
      "  Downloading dateparser-1.2.2-py3-none-any.whl.metadata (29 kB)\n",
      "Requirement already satisfied: laspy<3.0,>=2.0 in /opt/conda/envs/py311/lib/python3.11/site-packages (from laspy[lazrs]<3.0,>=2.0->py4dgeo) (2.6.1)\n",
      "Requirement already satisfied: matplotlib in /opt/conda/envs/py311/lib/python3.11/site-packages (from py4dgeo) (3.10.3)\n",
      "Requirement already satisfied: numpy in /opt/conda/envs/py311/lib/python3.11/site-packages (from py4dgeo) (2.1.2)\n",
      "Collecting pooch (from py4dgeo)\n",
      "  Downloading pooch-1.8.2-py3-none-any.whl.metadata (10 kB)\n",
      "Requirement already satisfied: requests in /opt/conda/envs/py311/lib/python3.11/site-packages (from py4dgeo) (2.32.5)\n",
      "Requirement already satisfied: seaborn in /opt/conda/envs/py311/lib/python3.11/site-packages (from py4dgeo) (0.13.2)\n",
      "Requirement already satisfied: scikit-learn in /opt/conda/envs/py311/lib/python3.11/site-packages (from py4dgeo) (1.7.0)\n",
      "Collecting vedo (from py4dgeo)\n",
      "  Downloading vedo-2025.5.4-py3-none-any.whl.metadata (14 kB)\n",
      "Collecting xdg (from py4dgeo)\n",
      "  Downloading xdg-6.0.0-py3-none-any.whl.metadata (1.3 kB)\n",
      "Requirement already satisfied: psutil in /opt/conda/envs/py311/lib/python3.11/site-packages (from py4dgeo) (5.9.0)\n",
      "Collecting lazrs<0.8.0,>=0.7.0 (from laspy[lazrs]<3.0,>=2.0->py4dgeo)\n",
      "  Downloading lazrs-0.7.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (601 bytes)\n",
      "Requirement already satisfied: python-dateutil>=2.7.0 in /opt/conda/envs/py311/lib/python3.11/site-packages (from dateparser->py4dgeo) (2.9.0.post0)\n",
      "Requirement already satisfied: pytz>=2024.2 in /opt/conda/envs/py311/lib/python3.11/site-packages (from dateparser->py4dgeo) (2025.2)\n",
      "Requirement already satisfied: regex>=2024.9.11 in /opt/conda/envs/py311/lib/python3.11/site-packages (from dateparser->py4dgeo) (2024.11.6)\n",
      "Collecting tzlocal>=0.2 (from dateparser->py4dgeo)\n",
      "  Downloading tzlocal-5.3.1-py3-none-any.whl.metadata (7.6 kB)\n",
      "Requirement already satisfied: six>=1.5 in /opt/conda/envs/py311/lib/python3.11/site-packages (from python-dateutil>=2.7.0->dateparser->py4dgeo) (1.17.0)\n",
      "Requirement already satisfied: contourpy>=1.0.1 in /opt/conda/envs/py311/lib/python3.11/site-packages (from matplotlib->py4dgeo) (1.3.2)\n",
      "Requirement already satisfied: cycler>=0.10 in /opt/conda/envs/py311/lib/python3.11/site-packages (from matplotlib->py4dgeo) (0.12.1)\n",
      "Requirement already satisfied: fonttools>=4.22.0 in /opt/conda/envs/py311/lib/python3.11/site-packages (from matplotlib->py4dgeo) (4.55.3)\n",
      "Requirement already satisfied: kiwisolver>=1.3.1 in /opt/conda/envs/py311/lib/python3.11/site-packages (from matplotlib->py4dgeo) (1.4.8)\n",
      "Requirement already satisfied: packaging>=20.0 in /opt/conda/envs/py311/lib/python3.11/site-packages (from matplotlib->py4dgeo) (24.2)\n",
      "Requirement already satisfied: pillow>=8 in /opt/conda/envs/py311/lib/python3.11/site-packages (from matplotlib->py4dgeo) (11.0.0)\n",
      "Requirement already satisfied: pyparsing>=2.3.1 in /opt/conda/envs/py311/lib/python3.11/site-packages (from matplotlib->py4dgeo) (3.2.3)\n",
      "Requirement already satisfied: platformdirs>=2.5.0 in /opt/conda/envs/py311/lib/python3.11/site-packages (from pooch->py4dgeo) (4.3.7)\n",
      "Requirement already satisfied: charset_normalizer<4,>=2 in /opt/conda/envs/py311/lib/python3.11/site-packages (from requests->py4dgeo) (3.4.3)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /opt/conda/envs/py311/lib/python3.11/site-packages (from requests->py4dgeo) (3.7)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/conda/envs/py311/lib/python3.11/site-packages (from requests->py4dgeo) (2.5.0)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/envs/py311/lib/python3.11/site-packages (from requests->py4dgeo) (2025.8.3)\n",
      "Requirement already satisfied: scipy>=1.8.0 in /opt/conda/envs/py311/lib/python3.11/site-packages (from scikit-learn->py4dgeo) (1.16.0)\n",
      "Requirement already satisfied: joblib>=1.2.0 in /opt/conda/envs/py311/lib/python3.11/site-packages (from scikit-learn->py4dgeo) (1.5.1)\n",
      "Requirement already satisfied: threadpoolctl>=3.1.0 in /opt/conda/envs/py311/lib/python3.11/site-packages (from scikit-learn->py4dgeo) (3.6.0)\n",
      "Requirement already satisfied: pandas>=1.2 in /opt/conda/envs/py311/lib/python3.11/site-packages (from seaborn->py4dgeo) (2.3.0)\n",
      "Requirement already satisfied: tzdata>=2022.7 in /opt/conda/envs/py311/lib/python3.11/site-packages (from pandas>=1.2->seaborn->py4dgeo) (2025.2)\n",
      "Collecting vtk (from vedo->py4dgeo)\n",
      "  Downloading vtk-9.5.2-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (5.6 kB)\n",
      "Requirement already satisfied: typing-extensions in /opt/conda/envs/py311/lib/python3.11/site-packages (from vedo->py4dgeo) (4.12.2)\n",
      "Requirement already satisfied: Pygments in /opt/conda/envs/py311/lib/python3.11/site-packages (from vedo->py4dgeo) (2.19.1)\n",
      "Downloading lazrs-0.7.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (639 kB)\n",
      "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m639.6/639.6 kB\u001b[0m \u001b[31m73.5 MB/s\u001b[0m  \u001b[33m0:00:00\u001b[0m\n",
      "\u001b[?25hDownloading dateparser-1.2.2-py3-none-any.whl (315 kB)\n",
      "Downloading tzlocal-5.3.1-py3-none-any.whl (18 kB)\n",
      "Downloading pooch-1.8.2-py3-none-any.whl (64 kB)\n",
      "Downloading vedo-2025.5.4-py3-none-any.whl (2.8 MB)\n",
      "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m2.8/2.8 MB\u001b[0m \u001b[31m36.0 MB/s\u001b[0m  \u001b[33m0:00:00\u001b[0m\n",
      "\u001b[?25hDownloading vtk-9.5.2-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (112.2 MB)\n",
      "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m112.2/112.2 MB\u001b[0m \u001b[31m77.3 MB/s\u001b[0m  \u001b[33m0:00:01\u001b[0mm0:00:01\u001b[0m0:01\u001b[0m\n",
      "\u001b[?25hDownloading xdg-6.0.0-py3-none-any.whl (3.9 kB)\n",
      "Building wheels for collected packages: py4dgeo\n",
      "  Building wheel for py4dgeo (pyproject.toml) ... \u001b[?25lerror\n",
      "  \u001b[1;31merror\u001b[0m: \u001b[1msubprocess-exited-with-error\u001b[0m\n",
      "  \n",
      "  \u001b[31m×\u001b[0m \u001b[32mBuilding wheel for py4dgeo \u001b[0m\u001b[1;32m(\u001b[0m\u001b[32mpyproject.toml\u001b[0m\u001b[1;32m)\u001b[0m did not run successfully.\n",
      "  \u001b[31m│\u001b[0m exit code: \u001b[1;36m1\u001b[0m\n",
      "  \u001b[31m╰─>\u001b[0m \u001b[31m[174 lines of output]\u001b[0m\n",
      "  \u001b[31m   \u001b[0m \u001b[33m\u001b[1;33mWARNING:\u001b[0m \u001b[33mUse cmake.version instead of cmake.minimum-version with scikit-build-core >= 0.8\u001b[0m\n",
      "  \u001b[31m   \u001b[0m \u001b[32m*** \u001b[1mscikit-build-core 0.11.6\u001b[0m using \u001b[34mCMake 4.1.2\u001b[39m\u001b[0m \u001b[31m(wheel)\u001b[0m\n",
      "  \u001b[31m   \u001b[0m \u001b[32m***\u001b[0m \u001b[1mConfiguring CMake...\u001b[0m\n",
      "  \u001b[31m   \u001b[0m loading initial cache file /tmp/tmpi9invwbn/build/CMakeInit.txt\n",
      "  \u001b[31m   \u001b[0m -- The CXX compiler identification is GNU 5.4.0\n",
      "  \u001b[31m   \u001b[0m -- Detecting CXX compiler ABI info\n",
      "  \u001b[31m   \u001b[0m -- Detecting CXX compiler ABI info - done\n",
      "  \u001b[31m   \u001b[0m -- Check for working CXX compiler: /usr/bin/g++ - skipped\n",
      "  \u001b[31m   \u001b[0m -- Detecting CXX compile features\n",
      "  \u001b[31m   \u001b[0m -- Detecting CXX compile features - done\n",
      "  \u001b[31m   \u001b[0m -- Found OpenMP_CXX: -fopenmp (found version \"4.0\")\n",
      "  \u001b[31m   \u001b[0m -- Found OpenMP: TRUE (found version \"4.0\")\n",
      "  \u001b[31m   \u001b[0m -- Found Python: /opt/conda/envs/py311/bin/python (found suitable version \"3.11.13\", minimum required is \"3.7\") found components: Interpreter Development.Module Development.Embed\n",
      "  \u001b[31m   \u001b[0m -- Performing Test HAS_FLTO\n",
      "  \u001b[31m   \u001b[0m -- Performing Test HAS_FLTO - Success\n",
      "  \u001b[31m   \u001b[0m -- Found pybind11: /opt/conda/envs/py311/lib/python3.11/site-packages/pybind11/include (found version \"2.13.6\")\n",
      "  \u001b[31m   \u001b[0m -- The following OPTIONAL packages have been found:\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m  * OpenMP\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m -- The following REQUIRED packages have been found:\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m  * Python (required version >= 3.7)\n",
      "  \u001b[31m   \u001b[0m  * pybind11\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m -- Configuring done (1.2s)\n",
      "  \u001b[31m   \u001b[0m -- Generating done (0.0s)\n",
      "  \u001b[31m   \u001b[0m -- Build files have been written to: /tmp/tmpi9invwbn/build\n",
      "  \u001b[31m   \u001b[0m \u001b[32m***\u001b[0m \u001b[1mBuilding project with \u001b[34mNinja\u001b[39m...\u001b[0m\n",
      "  \u001b[31m   \u001b[0m [1/11] Building CXX object CMakeFiles/py4dgeo.dir/lib/octree.cpp.o\n",
      "  \u001b[31m   \u001b[0m FAILED: CMakeFiles/py4dgeo.dir/lib/octree.cpp.o\n",
      "  \u001b[31m   \u001b[0m /usr/bin/g++  -pthread -B /opt/conda/envs/py311/compiler_compat -DEIGEN_DONT_PARALLELIZE -DPY4DGEO_WITH_OPENMP -I/tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/include -I/tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/ext/eigen -I/tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/ext/nanoflann/include -O3 -DNDEBUG -std=gnu++1z -fPIC -fopenmp -MD -MT CMakeFiles/py4dgeo.dir/lib/octree.cpp.o -MF CMakeFiles/py4dgeo.dir/lib/octree.cpp.o.d -o CMakeFiles/py4dgeo.dir/lib/octree.cpp.o -c /tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/lib/octree.cpp\n",
      "  \u001b[31m   \u001b[0m In file included from /tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/lib/octree.cpp:1:0:\n",
      "  \u001b[31m   \u001b[0m /tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/include/py4dgeo/octree.hpp:12:20: fatal error: optional: No such file or directory\n",
      "  \u001b[31m   \u001b[0m compilation terminated.\n",
      "  \u001b[31m   \u001b[0m [2/11] Building CXX object CMakeFiles/py4dgeo.dir/lib/epoch.cpp.o\n",
      "  \u001b[31m   \u001b[0m FAILED: CMakeFiles/py4dgeo.dir/lib/epoch.cpp.o\n",
      "  \u001b[31m   \u001b[0m /usr/bin/g++  -pthread -B /opt/conda/envs/py311/compiler_compat -DEIGEN_DONT_PARALLELIZE -DPY4DGEO_WITH_OPENMP -I/tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/include -I/tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/ext/eigen -I/tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/ext/nanoflann/include -O3 -DNDEBUG -std=gnu++1z -fPIC -fopenmp -MD -MT CMakeFiles/py4dgeo.dir/lib/epoch.cpp.o -MF CMakeFiles/py4dgeo.dir/lib/epoch.cpp.o.d -o CMakeFiles/py4dgeo.dir/lib/epoch.cpp.o -c /tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/lib/epoch.cpp\n",
      "  \u001b[31m   \u001b[0m In file included from /tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/include/py4dgeo/epoch.hpp:4:0,\n",
      "  \u001b[31m   \u001b[0m                  from /tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/lib/epoch.cpp:1:\n",
      "  \u001b[31m   \u001b[0m /tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/include/py4dgeo/octree.hpp:12:20: fatal error: optional: No such file or directory\n",
      "  \u001b[31m   \u001b[0m compilation terminated.\n",
      "  \u001b[31m   \u001b[0m [3/11] Building CXX object CMakeFiles/py4dgeo.dir/lib/directions.cpp.o\n",
      "  \u001b[31m   \u001b[0m FAILED: CMakeFiles/py4dgeo.dir/lib/directions.cpp.o\n",
      "  \u001b[31m   \u001b[0m /usr/bin/g++  -pthread -B /opt/conda/envs/py311/compiler_compat -DEIGEN_DONT_PARALLELIZE -DPY4DGEO_WITH_OPENMP -I/tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/include -I/tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/ext/eigen -I/tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/ext/nanoflann/include -O3 -DNDEBUG -std=gnu++1z -fPIC -fopenmp -MD -MT CMakeFiles/py4dgeo.dir/lib/directions.cpp.o -MF CMakeFiles/py4dgeo.dir/lib/directions.cpp.o.d -o CMakeFiles/py4dgeo.dir/lib/directions.cpp.o -c /tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/lib/directions.cpp\n",
      "  \u001b[31m   \u001b[0m In file included from /tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/include/py4dgeo/epoch.hpp:4:0,\n",
      "  \u001b[31m   \u001b[0m                  from /tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/include/py4dgeo/compute.hpp:3,\n",
      "  \u001b[31m   \u001b[0m                  from /tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/lib/directions.cpp:1:\n",
      "  \u001b[31m   \u001b[0m /tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/include/py4dgeo/octree.hpp:12:20: fatal error: optional: No such file or directory\n",
      "  \u001b[31m   \u001b[0m compilation terminated.\n",
      "  \u001b[31m   \u001b[0m [4/11] Building CXX object CMakeFiles/py4dgeo.dir/lib/registration.cpp.o\n",
      "  \u001b[31m   \u001b[0m FAILED: CMakeFiles/py4dgeo.dir/lib/registration.cpp.o\n",
      "  \u001b[31m   \u001b[0m /usr/bin/g++  -pthread -B /opt/conda/envs/py311/compiler_compat -DEIGEN_DONT_PARALLELIZE -DPY4DGEO_WITH_OPENMP -I/tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/include -I/tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/ext/eigen -I/tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/ext/nanoflann/include -O3 -DNDEBUG -std=gnu++1z -fPIC -fopenmp -MD -MT CMakeFiles/py4dgeo.dir/lib/registration.cpp.o -MF CMakeFiles/py4dgeo.dir/lib/registration.cpp.o.d -o CMakeFiles/py4dgeo.dir/lib/registration.cpp.o -c /tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/lib/registration.cpp\n",
      "  \u001b[31m   \u001b[0m In file included from /tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/include/py4dgeo/epoch.hpp:4:0,\n",
      "  \u001b[31m   \u001b[0m                  from /tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/include/py4dgeo/compute.hpp:3,\n",
      "  \u001b[31m   \u001b[0m                  from /tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/include/py4dgeo/registration.hpp:3,\n",
      "  \u001b[31m   \u001b[0m                  from /tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/lib/registration.cpp:1:\n",
      "  \u001b[31m   \u001b[0m /tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/include/py4dgeo/octree.hpp:12:20: fatal error: optional: No such file or directory\n",
      "  \u001b[31m   \u001b[0m compilation terminated.\n",
      "  \u001b[31m   \u001b[0m [5/11] Building CXX object CMakeFiles/py4dgeo.dir/lib/distances.cpp.o\n",
      "  \u001b[31m   \u001b[0m FAILED: CMakeFiles/py4dgeo.dir/lib/distances.cpp.o\n",
      "  \u001b[31m   \u001b[0m /usr/bin/g++  -pthread -B /opt/conda/envs/py311/compiler_compat -DEIGEN_DONT_PARALLELIZE -DPY4DGEO_WITH_OPENMP -I/tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/include -I/tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/ext/eigen -I/tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/ext/nanoflann/include -O3 -DNDEBUG -std=gnu++1z -fPIC -fopenmp -MD -MT CMakeFiles/py4dgeo.dir/lib/distances.cpp.o -MF CMakeFiles/py4dgeo.dir/lib/distances.cpp.o.d -o CMakeFiles/py4dgeo.dir/lib/distances.cpp.o -c /tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/lib/distances.cpp\n",
      "  \u001b[31m   \u001b[0m In file included from /tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/include/py4dgeo/epoch.hpp:4:0,\n",
      "  \u001b[31m   \u001b[0m                  from /tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/include/py4dgeo/compute.hpp:3,\n",
      "  \u001b[31m   \u001b[0m                  from /tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/lib/distances.cpp:1:\n",
      "  \u001b[31m   \u001b[0m /tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/include/py4dgeo/octree.hpp:12:20: fatal error: optional: No such file or directory\n",
      "  \u001b[31m   \u001b[0m compilation terminated.\n",
      "  \u001b[31m   \u001b[0m [6/11] Building CXX object CMakeFiles/py4dgeo.dir/lib/segmentation.cpp.o\n",
      "  \u001b[31m   \u001b[0m FAILED: CMakeFiles/py4dgeo.dir/lib/segmentation.cpp.o\n",
      "  \u001b[31m   \u001b[0m /usr/bin/g++  -pthread -B /opt/conda/envs/py311/compiler_compat -DEIGEN_DONT_PARALLELIZE -DPY4DGEO_WITH_OPENMP -I/tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/include -I/tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/ext/eigen -I/tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/ext/nanoflann/include -O3 -DNDEBUG -std=gnu++1z -fPIC -fopenmp -MD -MT CMakeFiles/py4dgeo.dir/lib/segmentation.cpp.o -MF CMakeFiles/py4dgeo.dir/lib/segmentation.cpp.o.d -o CMakeFiles/py4dgeo.dir/lib/segmentation.cpp.o -c /tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/lib/segmentation.cpp\n",
      "  \u001b[31m   \u001b[0m In file included from /tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/include/py4dgeo/epoch.hpp:4:0,\n",
      "  \u001b[31m   \u001b[0m                  from /tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/include/py4dgeo/segmentation.hpp:3,\n",
      "  \u001b[31m   \u001b[0m                  from /tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/lib/segmentation.cpp:1:\n",
      "  \u001b[31m   \u001b[0m /tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/include/py4dgeo/octree.hpp:12:20: fatal error: optional: No such file or directory\n",
      "  \u001b[31m   \u001b[0m compilation terminated.\n",
      "  \u001b[31m   \u001b[0m [7/11] Building CXX object CMakeFiles/py4dgeo.dir/lib/searchtree.cpp.o\n",
      "  \u001b[31m   \u001b[0m FAILED: CMakeFiles/py4dgeo.dir/lib/searchtree.cpp.o\n",
      "  \u001b[31m   \u001b[0m /usr/bin/g++  -pthread -B /opt/conda/envs/py311/compiler_compat -DEIGEN_DONT_PARALLELIZE -DPY4DGEO_WITH_OPENMP -I/tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/include -I/tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/ext/eigen -I/tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/ext/nanoflann/include -O3 -DNDEBUG -std=gnu++1z -fPIC -fopenmp -MD -MT CMakeFiles/py4dgeo.dir/lib/searchtree.cpp.o -MF CMakeFiles/py4dgeo.dir/lib/searchtree.cpp.o.d -o CMakeFiles/py4dgeo.dir/lib/searchtree.cpp.o -c /tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/lib/searchtree.cpp\n",
      "  \u001b[31m   \u001b[0m In file included from /tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/include/py4dgeo/epoch.hpp:4:0,\n",
      "  \u001b[31m   \u001b[0m                  from /tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/lib/searchtree.cpp:3:\n",
      "  \u001b[31m   \u001b[0m /tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/include/py4dgeo/octree.hpp:12:20: fatal error: optional: No such file or directory\n",
      "  \u001b[31m   \u001b[0m compilation terminated.\n",
      "  \u001b[31m   \u001b[0m [8/11] Building CXX object CMakeFiles/py4dgeo.dir/lib/kdtree.cpp.o\n",
      "  \u001b[31m   \u001b[0m FAILED: CMakeFiles/py4dgeo.dir/lib/kdtree.cpp.o\n",
      "  \u001b[31m   \u001b[0m /usr/bin/g++  -pthread -B /opt/conda/envs/py311/compiler_compat -DEIGEN_DONT_PARALLELIZE -DPY4DGEO_WITH_OPENMP -I/tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/include -I/tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/ext/eigen -I/tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/ext/nanoflann/include -O3 -DNDEBUG -std=gnu++1z -fPIC -fopenmp -MD -MT CMakeFiles/py4dgeo.dir/lib/kdtree.cpp.o -MF CMakeFiles/py4dgeo.dir/lib/kdtree.cpp.o.d -o CMakeFiles/py4dgeo.dir/lib/kdtree.cpp.o -c /tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/lib/kdtree.cpp\n",
      "  \u001b[31m   \u001b[0m In file included from /tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/ext/eigen/Eigen/Core:162:0,\n",
      "  \u001b[31m   \u001b[0m                  from /tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/include/py4dgeo/py4dgeo.hpp:3,\n",
      "  \u001b[31m   \u001b[0m                  from /tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/include/py4dgeo/kdtree.hpp:3,\n",
      "  \u001b[31m   \u001b[0m                  from /tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/lib/kdtree.cpp:5:\n",
      "  \u001b[31m   \u001b[0m /tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/ext/eigen/Eigen/src/Core/util/Meta.h:504:25: error: ‘invoke_result’ in namespace ‘std’ does not name a template type\n",
      "  \u001b[31m   \u001b[0m    typedef typename std::invoke_result<F, ArgTypes...>::type type1;\n",
      "  \u001b[31m   \u001b[0m                          ^\n",
      "  \u001b[31m   \u001b[0m /tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/ext/eigen/Eigen/src/Core/util/Meta.h:504:38: error: expected unqualified-id before ‘<’ token\n",
      "  \u001b[31m   \u001b[0m    typedef typename std::invoke_result<F, ArgTypes...>::type type1;\n",
      "  \u001b[31m   \u001b[0m                                       ^\n",
      "  \u001b[31m   \u001b[0m /tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/ext/eigen/Eigen/src/Core/util/Meta.h:505:31: error: ‘type1’ was not declared in this scope\n",
      "  \u001b[31m   \u001b[0m    typedef typename remove_all<type1>::type type;\n",
      "  \u001b[31m   \u001b[0m                                ^\n",
      "  \u001b[31m   \u001b[0m /tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/ext/eigen/Eigen/src/Core/util/Meta.h:505:36: error: template argument 1 is invalid\n",
      "  \u001b[31m   \u001b[0m    typedef typename remove_all<type1>::type type;\n",
      "  \u001b[31m   \u001b[0m                                     ^\n",
      "  \u001b[31m   \u001b[0m In file included from /tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/ext/eigen/Eigen/Core:162:0,\n",
      "  \u001b[31m   \u001b[0m                  from /tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/include/py4dgeo/py4dgeo.hpp:3,\n",
      "  \u001b[31m   \u001b[0m                  from /tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/include/py4dgeo/kdtree.hpp:3,\n",
      "  \u001b[31m   \u001b[0m                  from /tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/lib/kdtree.cpp:5:\n",
      "  \u001b[31m   \u001b[0m /tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/ext/eigen/Eigen/src/Core/util/Meta.h:616:25: error: ‘invoke_result’ in namespace ‘std’ does not name a template type\n",
      "  \u001b[31m   \u001b[0m    typedef typename std::invoke_result<F, ArgTypes...>::type type1;\n",
      "  \u001b[31m   \u001b[0m                          ^\n",
      "  \u001b[31m   \u001b[0m /tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/ext/eigen/Eigen/src/Core/util/Meta.h:616:38: error: expected unqualified-id before ‘<’ token\n",
      "  \u001b[31m   \u001b[0m    typedef typename std::invoke_result<F, ArgTypes...>::type type1;\n",
      "  \u001b[31m   \u001b[0m                                       ^\n",
      "  \u001b[31m   \u001b[0m /tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/ext/eigen/Eigen/src/Core/util/Meta.h:617:31: error: ‘type1’ was not declared in this scope\n",
      "  \u001b[31m   \u001b[0m    typedef typename remove_all<type1>::type type;\n",
      "  \u001b[31m   \u001b[0m                                ^\n",
      "  \u001b[31m   \u001b[0m /tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/ext/eigen/Eigen/src/Core/util/Meta.h:617:36: error: template argument 1 is invalid\n",
      "  \u001b[31m   \u001b[0m    typedef typename remove_all<type1>::type type;\n",
      "  \u001b[31m   \u001b[0m                                     ^\n",
      "  \u001b[31m   \u001b[0m [9/11] Building CXX object CMakeFiles/_py4dgeo.dir/src/py4dgeo/py4dgeo_python.cpp.o\n",
      "  \u001b[31m   \u001b[0m FAILED: CMakeFiles/_py4dgeo.dir/src/py4dgeo/py4dgeo_python.cpp.o\n",
      "  \u001b[31m   \u001b[0m /usr/bin/g++  -pthread -B /opt/conda/envs/py311/compiler_compat -DEIGEN_DONT_PARALLELIZE -DPY4DGEO_WITH_OPENMP -D_py4dgeo_EXPORTS -I/tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/include -I/tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/ext/eigen -I/tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/ext/nanoflann/include -isystem /opt/conda/envs/py311/include/python3.11 -isystem /opt/conda/envs/py311/lib/python3.11/site-packages/pybind11/include -O3 -DNDEBUG -std=gnu++1z -fPIC -fvisibility=hidden -flto -fno-fat-lto-objects -fopenmp -MD -MT CMakeFiles/_py4dgeo.dir/src/py4dgeo/py4dgeo_python.cpp.o -MF CMakeFiles/_py4dgeo.dir/src/py4dgeo/py4dgeo_python.cpp.o.d -o CMakeFiles/_py4dgeo.dir/src/py4dgeo/py4dgeo_python.cpp.o -c /tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/src/py4dgeo/py4dgeo_python.cpp\n",
      "  \u001b[31m   \u001b[0m In file included from /tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/ext/eigen/Eigen/Core:162:0,\n",
      "  \u001b[31m   \u001b[0m                  from /opt/conda/envs/py311/lib/python3.11/site-packages/pybind11/include/pybind11/eigen/matrix.h:28,\n",
      "  \u001b[31m   \u001b[0m                  from /opt/conda/envs/py311/lib/python3.11/site-packages/pybind11/include/pybind11/eigen.h:12,\n",
      "  \u001b[31m   \u001b[0m                  from /tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/src/py4dgeo/py4dgeo_python.cpp:1:\n",
      "  \u001b[31m   \u001b[0m /tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/ext/eigen/Eigen/src/Core/util/Meta.h:504:25: error: ‘invoke_result’ in namespace ‘std’ does not name a template type\n",
      "  \u001b[31m   \u001b[0m    typedef typename std::invoke_result<F, ArgTypes...>::type type1;\n",
      "  \u001b[31m   \u001b[0m                          ^\n",
      "  \u001b[31m   \u001b[0m /tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/ext/eigen/Eigen/src/Core/util/Meta.h:504:38: error: expected unqualified-id before ‘<’ token\n",
      "  \u001b[31m   \u001b[0m    typedef typename std::invoke_result<F, ArgTypes...>::type type1;\n",
      "  \u001b[31m   \u001b[0m                                       ^\n",
      "  \u001b[31m   \u001b[0m /tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/ext/eigen/Eigen/src/Core/util/Meta.h:505:31: error: ‘type1’ was not declared in this scope\n",
      "  \u001b[31m   \u001b[0m    typedef typename remove_all<type1>::type type;\n",
      "  \u001b[31m   \u001b[0m                                ^\n",
      "  \u001b[31m   \u001b[0m /tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/ext/eigen/Eigen/src/Core/util/Meta.h:505:36: error: template argument 1 is invalid\n",
      "  \u001b[31m   \u001b[0m    typedef typename remove_all<type1>::type type;\n",
      "  \u001b[31m   \u001b[0m                                     ^\n",
      "  \u001b[31m   \u001b[0m In file included from /tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/ext/eigen/Eigen/Core:162:0,\n",
      "  \u001b[31m   \u001b[0m                  from /opt/conda/envs/py311/lib/python3.11/site-packages/pybind11/include/pybind11/eigen/matrix.h:28,\n",
      "  \u001b[31m   \u001b[0m                  from /opt/conda/envs/py311/lib/python3.11/site-packages/pybind11/include/pybind11/eigen.h:12,\n",
      "  \u001b[31m   \u001b[0m                  from /tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/src/py4dgeo/py4dgeo_python.cpp:1:\n",
      "  \u001b[31m   \u001b[0m /tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/ext/eigen/Eigen/src/Core/util/Meta.h:616:25: error: ‘invoke_result’ in namespace ‘std’ does not name a template type\n",
      "  \u001b[31m   \u001b[0m    typedef typename std::invoke_result<F, ArgTypes...>::type type1;\n",
      "  \u001b[31m   \u001b[0m                          ^\n",
      "  \u001b[31m   \u001b[0m /tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/ext/eigen/Eigen/src/Core/util/Meta.h:616:38: error: expected unqualified-id before ‘<’ token\n",
      "  \u001b[31m   \u001b[0m    typedef typename std::invoke_result<F, ArgTypes...>::type type1;\n",
      "  \u001b[31m   \u001b[0m                                       ^\n",
      "  \u001b[31m   \u001b[0m /tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/ext/eigen/Eigen/src/Core/util/Meta.h:617:31: error: ‘type1’ was not declared in this scope\n",
      "  \u001b[31m   \u001b[0m    typedef typename remove_all<type1>::type type;\n",
      "  \u001b[31m   \u001b[0m                                ^\n",
      "  \u001b[31m   \u001b[0m /tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/ext/eigen/Eigen/src/Core/util/Meta.h:617:36: error: template argument 1 is invalid\n",
      "  \u001b[31m   \u001b[0m    typedef typename remove_all<type1>::type type;\n",
      "  \u001b[31m   \u001b[0m                                     ^\n",
      "  \u001b[31m   \u001b[0m In file included from /tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/include/py4dgeo/epoch.hpp:4:0,\n",
      "  \u001b[31m   \u001b[0m                  from /tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/include/py4dgeo/compute.hpp:3,\n",
      "  \u001b[31m   \u001b[0m                  from /tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/src/py4dgeo/py4dgeo_python.cpp:11:\n",
      "  \u001b[31m   \u001b[0m /tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/include/py4dgeo/octree.hpp:93:67: error: ‘grid_size’ declared as an ‘inline’ field\n",
      "  \u001b[31m   \u001b[0m    inline static constexpr unsigned int grid_size = (1 << max_depth);\n",
      "  \u001b[31m   \u001b[0m                                                                    ^\n",
      "  \u001b[31m   \u001b[0m /tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/include/py4dgeo/octree.hpp:103:7: error: ‘bit_shift’ declared as an ‘inline’ field\n",
      "  \u001b[31m   \u001b[0m      }();\n",
      "  \u001b[31m   \u001b[0m        ^\n",
      "  \u001b[31m   \u001b[0m /tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/include/py4dgeo/octree.hpp:103:7: error: call to non-constexpr function ‘py4dgeo::Octree::<lambda()>’\n",
      "  \u001b[31m   \u001b[0m /tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/include/py4dgeo/octree.hpp:112:38: error: ‘dilate8_table’ declared as an ‘inline’ field\n",
      "  \u001b[31m   \u001b[0m      make_dilate_table<SpatialKey, 8>(); // 256 entries\n",
      "  \u001b[31m   \u001b[0m                                       ^\n",
      "  \u001b[31m   \u001b[0m /tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/include/py4dgeo/octree.hpp:112:38: error: ‘constexpr std::array<T, TABLE_SIZE> py4dgeo::make_dilate_table() [with T = unsigned int; unsigned int BITS = 8u; long unsigned int TABLE_SIZE = 256ul]’ called in a constant expression\n",
      "  \u001b[31m   \u001b[0m /tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/include/py4dgeo/octree.hpp:35:1: note: ‘constexpr std::array<T, TABLE_SIZE> py4dgeo::make_dilate_table() [with T = unsigned int; unsigned int BITS = 8u; long unsigned int TABLE_SIZE = 256ul]’ is not usable as a constexpr function because:\n",
      "  \u001b[31m   \u001b[0m  make_dilate_table()\n",
      "  \u001b[31m   \u001b[0m  ^\n",
      "  \u001b[31m   \u001b[0m /tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/include/py4dgeo/octree.hpp:35:1: sorry, unimplemented: unexpected AST of kind loop_expr\n",
      "  \u001b[31m   \u001b[0m /tmp/pip-install-3gs6my1q/py4dgeo_c248e876560d490c8e636cf2997bbeb1/include/py4dgeo/octree.hpp:35: confused by earlier errors, bailing out\n",
      "  \u001b[31m   \u001b[0m ninja: build stopped: subcommand failed.\n",
      "  \u001b[31m   \u001b[0m \u001b[31m\n",
      "  \u001b[31m   \u001b[0m \u001b[1m***\u001b[0m \u001b[31mCMake build failed\u001b[0m\n",
      "  \u001b[31m   \u001b[0m \u001b[31m[end of output]\u001b[0m\n",
      "  \n",
      "  \u001b[1;35mnote\u001b[0m: This error originates from a subprocess, and is likely not a problem with pip.\n",
      "\u001b[31m  ERROR: Failed building wheel for py4dgeo\u001b[0m\u001b[31m\n",
      "\u001b[0m\u001b[?25hFailed to build py4dgeo\n",
      "\u001b[33mWARNING: Ignoring invalid distribution ~ympy (/opt/conda/envs/py311/lib/python3.11/site-packages)\u001b[0m\u001b[33m\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution ~ympy (/opt/conda/envs/py311/lib/python3.11/site-packages)\u001b[0m\u001b[33m\r\n",
      "\u001b[0m\r\n",
      "\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m A new release of pip is available: \u001b[0m\u001b[31;49m25.2\u001b[0m\u001b[39;49m -> \u001b[0m\u001b[32;49m25.3\u001b[0m\r\n",
      "\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m To update, run: \u001b[0m\u001b[32;49m/opt/conda/envs/py311/bin/python -m pip install --upgrade pip\u001b[0m\r\n",
      "\u001b[1;31merror\u001b[0m: \u001b[1mfailed-wheel-build-for-install\u001b[0m\r\n",
      "\r\n",
      "\u001b[31m×\u001b[0m Failed to build installable wheels for some pyproject.toml based projects\r\n",
      "\u001b[31m╰─>\u001b[0m py4dgeo\r\n"
     ]
    }
   ],
   "source": [
    "import sys\n",
    "!{sys.executable} -m pip install py4dgeo --no-cache-dir\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "880ed749",
   "metadata": {
    "ExecuteTime": {
     "end_time": "2025-10-29T23:36:55.287381Z",
     "start_time": "2025-10-29T23:36:55.242945Z"
    }
   },
   "outputs": [
    {
     "ename": "ModuleNotFoundError",
     "evalue": "No module named 'py4dgeo'",
     "output_type": "error",
     "traceback": [
      "\u001b[31m---------------------------------------------------------------------------\u001b[39m",
      "\u001b[31mModuleNotFoundError\u001b[39m                       Traceback (most recent call last)",
      "\u001b[36mCell\u001b[39m\u001b[36m \u001b[39m\u001b[32mIn[3]\u001b[39m\u001b[32m, line 3\u001b[39m\n\u001b[32m      1\u001b[39m \u001b[38;5;66;03m# import required modules\u001b[39;00m\n\u001b[32m      2\u001b[39m \u001b[38;5;28;01mimport\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34;01mos\u001b[39;00m\n\u001b[32m----> \u001b[39m\u001b[32m3\u001b[39m \u001b[38;5;28;01mimport\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34;01mpy4dgeo\u001b[39;00m\n\u001b[32m      4\u001b[39m \u001b[38;5;28;01mimport\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34;01mnumpy\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;28;01mas\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34;01mnp\u001b[39;00m\n\u001b[32m      5\u001b[39m \u001b[38;5;28;01mimport\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34;01mmatplotlib\u001b[39;00m\u001b[34;01m.\u001b[39;00m\u001b[34;01mpyplot\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;28;01mas\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34;01mplt\u001b[39;00m\n",
      "\u001b[31mModuleNotFoundError\u001b[39m: No module named 'py4dgeo'"
     ]
    }
   ],
   "source": [
    "# import required modules\n",
    "import os\n",
    "import py4dgeo\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import matplotlib.dates as mdates\n",
    "from datetime import datetime, timedelta\n",
    "\n",
    "# add the script assets folder to the path, so that we can import the functions created there\n",
    "import sys\n",
    "from pathlib import Path\n",
    "# sys.path.insert(0, str((Path.cwd() / \"..\" / \"..\" / \"assets\" / \"python_functions\").resolve()))\n",
    "\n",
    "# import point cloud functions\n",
    "import pointcloud_functions as pcfuncs\n",
    "\n",
    "# specify the data path\n",
    "data_dir = '../raw_data'\n",
    "\n",
    "# check if the data path exists\n",
    "if not os.path.exists(data_dir):\n",
    "    raise Exception('Data path does not exist. Please make sure to specify the correct path.')\n",
    "\n",
    "# derive the file paths and read in the data\n",
    "pc_file_2020 = f'{data_dir}/ahk_2020_uls.laz'\n",
    "pc_file_2021 = f'{data_dir}/ahk_2021_uls.laz'\n",
    "\n",
    "# read the point clouds into numpy arrays\n",
    "#pc_2020 = pcfuncs.read_las(pc_file_2020)\n",
    "#pc_2021 = pcfuncs.read_las(pc_file_2021)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python py311",
   "language": "python",
   "name": "py311"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.13"
  },
  "toc": {
   "base_numbering": 1,
   "nav_menu": {},
   "number_sections": true,
   "sideBar": true,
   "skip_h1_title": false,
   "title_cell": "Table of Contents",
   "title_sidebar": "Contents",
   "toc_cell": false,
   "toc_position": {},
   "toc_section_display": true,
   "toc_window_display": false
  },
  "varInspector": {
   "cols": {
    "lenName": 16,
    "lenType": 16,
    "lenVar": 40
   },
   "kernels_config": {
    "python": {
     "delete_cmd_postfix": "",
     "delete_cmd_prefix": "del ",
     "library": "var_list.py",
     "varRefreshCmd": "print(var_dic_list())"
    },
    "r": {
     "delete_cmd_postfix": ") ",
     "delete_cmd_prefix": "rm(",
     "library": "var_list.r",
     "varRefreshCmd": "cat(var_dic_list()) "
    }
   },
   "types_to_exclude": [
    "module",
    "function",
    "builtin_function_or_method",
    "instance",
    "_Feature"
   ],
   "window_display": false
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
